// <auto-generated />
using System;
using Ecommerce.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ecommerce.DataAccess.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20260106144433_SeededDataChangeAndCategoryNewAttribute")]
    partial class SeededDataChangeAndCategoryNewAttribute
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ecommerce.Entities.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "92e67dee-c904-439f-bba6-96eace7193be",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "86e8c2f4-2099-49e4-bcc2-5539f0b21ace",
                            Email = "mhmdabohend@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Mohamed Abohend",
                            NormalizedEmail = "MHMDABOHEND@GMAIL.COM",
                            NormalizedUserName = "MHMDABOHEND@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMz5qSSjQdXqWQKqxL/aIbMXzCPEKKOaT3CuaxaREWOi62dApoOL0ex9tIjVhfaCyA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "94b423d4-6c86-4a3d-bd8e-f1432e01a469",
                            TwoFactorEnabled = false,
                            UserName = "mhmdabohend@gmail.com"
                        },
                        new
                        {
                            Id = "034f768e-f2f4-40d6-a612-3f95674f1ac5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7f4dd870-a30c-488a-9fb2-0688846aaba5",
                            Email = "saeedabohend@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Saeed Abohend",
                            NormalizedEmail = "SAEEDABOHEND@EXAMPLE.COM",
                            NormalizedUserName = "SAEEDABOHEND@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGxvVbYTiVVyysBGQZ75aRxfIX4OqAkFaCUrPZcPVu1UB6VNJmZZenaOOHtcgW+Oag==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9dce36b6-74b2-4f05-8936-f8186a50de02",
                            TwoFactorEnabled = false,
                            UserName = "saeedabohend@example.com"
                        },
                        new
                        {
                            Id = "b0cf6801-a4b0-4fde-a769-e981a0e8c6ed",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1938814f-c693-4bc6-9504-be0d01d2a7db",
                            Email = "abdoabohend@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "AbdoAbohend",
                            NormalizedEmail = "ABDOABOHEND@EXAMPLE.COM",
                            NormalizedUserName = "ABDOABOHEND@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAENW8IZcambkRvXASQgU/i89gg2c2UPHHpBdaWnT+iop14TkfJNJtcL3l/HHmsN1Vdw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a058e9bd-f1e5-4d93-9e1e-f2ad7bfc7737",
                            TwoFactorEnabled = false,
                            UserName = "abdoabohend@example.com"
                        },
                        new
                        {
                            Id = "c9bfe5ec-f047-400b-bef4-0a0ffc70edb5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5d173834-eb21-4362-8d2d-457bc8c63c04",
                            Email = "ziadabohend@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Ziad Abohend",
                            NormalizedEmail = "ZIADABOHEND@EXAMPLE.COM",
                            NormalizedUserName = "ZIADABOHEND@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMZUl5wmp35QquspokzWSd78JBmHHvVvc95kIC5aFe4k6ok7lLDntAg42HmAITmPfA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "cc808973-b569-4622-ac0e-17abe89fabe0",
                            TwoFactorEnabled = false,
                            UserName = "ziadabohend@example.com"
                        });
                });

            modelBuilder.Entity("Ecommerce.Entities.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Fresh fruits",
                            Image = "images/categories/Fruits.png",
                            Name = "Fruits"
                        },
                        new
                        {
                            Id = 2,
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Fresh vegetables",
                            Image = "images/categories/Vegetables.jpg",
                            Name = "Vegetables"
                        },
                        new
                        {
                            Id = 3,
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "High quality bread",
                            Image = "images/categories/Bread.jpg",
                            Name = "Bread"
                        },
                        new
                        {
                            Id = 4,
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "All meat types",
                            Image = "images/categories/Meat.jpg",
                            Name = "Meat"
                        });
                });

            modelBuilder.Entity("Ecommerce.Entities.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Carrier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentIntentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SessionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ShippingDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrackingNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Ecommerce.Entities.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Ecommerce.Entities.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Fresh grapes",
                            Image = "images/products/grapes.jpg",
                            Name = "Grapes",
                            Price = 4.99m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Fresh Raspberries",
                            Image = "images/products/Raspberries.jpg",
                            Name = "Raspberries",
                            Price = 5.99m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "Fresh brocoli",
                            Image = "images/products/Brocoli.jpg",
                            Name = "Brocoli",
                            Price = 2.5m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "High quality potatoes",
                            Image = "images/products/Potatoes.jpg",
                            Name = "Potatoes",
                            Price = 1.4m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Description = "Wellbacked breadsticks",
                            Image = "images/products/Breadsticks.jpg",
                            Name = "Breadsticks",
                            Price = 1.93m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Description = "Wellbacked croissant",
                            Image = "images/products/Croissant.jpg",
                            Name = "Croissant",
                            Price = 2.14m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            Description = "Basic cuts of beef",
                            Image = "images/products/Beef.jpg",
                            Name = "Beef",
                            Price = 9.14m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            Description = "Basic cuts of lamp meat",
                            Image = "images/products/Lamp.webp",
                            Name = "Lamp",
                            Price = 10.45m
                        });
                });

            modelBuilder.Entity("Ecommerce.Entities.Models.ShoppingCartItem", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.HasKey("ProductId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ShoppingCartItems");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = "6be9d851-4496-4d3c-878b-c5816d15132c",
                            Name = "admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "df695ebc-f8b0-460a-883e-a53004f3f224",
                            Name = "customer",
                            NormalizedName = "CUSTOMER"
                        },
                        new
                        {
                            Id = "2e42297d-e84c-4778-820c-af61bd9949ec",
                            Name = "editor",
                            NormalizedName = "EDITOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RoleId", "UserId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            RoleId = "6be9d851-4496-4d3c-878b-c5816d15132c",
                            UserId = "92e67dee-c904-439f-bba6-96eace7193be"
                        },
                        new
                        {
                            RoleId = "df695ebc-f8b0-460a-883e-a53004f3f224",
                            UserId = "034f768e-f2f4-40d6-a612-3f95674f1ac5"
                        },
                        new
                        {
                            RoleId = "df695ebc-f8b0-460a-883e-a53004f3f224",
                            UserId = "b0cf6801-a4b0-4fde-a769-e981a0e8c6ed"
                        },
                        new
                        {
                            RoleId = "df695ebc-f8b0-460a-883e-a53004f3f224",
                            UserId = "c9bfe5ec-f047-400b-bef4-0a0ffc70edb5"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("Ecommerce.Entities.Models.Order", b =>
                {
                    b.HasOne("Ecommerce.Entities.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ecommerce.Entities.Models.OrderItem", b =>
                {
                    b.HasOne("Ecommerce.Entities.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ecommerce.Entities.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Ecommerce.Entities.Models.Product", b =>
                {
                    b.HasOne("Ecommerce.Entities.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Ecommerce.Entities.Models.ShoppingCartItem", b =>
                {
                    b.HasOne("Ecommerce.Entities.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ecommerce.Entities.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ecommerce.Entities.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
