// <auto-generated />
using System;
using Ecommerce.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ecommerce.DataAccess.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20260111182734_ContactModelsAdded")]
    partial class ContactModelsAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ecommerce.Entities.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "3d482e40-06df-4e49-9c41-68bad89689c3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "44407855-1f82-4edd-87c2-5d3e752367b7",
                            Email = "mhmdabohend@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Mohamed Abohend",
                            NormalizedEmail = "MHMDABOHEND@GMAIL.COM",
                            NormalizedUserName = "MHMDABOHEND@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGHgga/rIVbnodPTZRauAv3oMryXipfsW9Hp+YzTrG0yX4RFNopj078HRvo+IPNz8A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4c1c1179-0af5-4d78-9794-f7b6da8cb946",
                            TwoFactorEnabled = false,
                            UserName = "mhmdabohend@gmail.com"
                        },
                        new
                        {
                            Id = "e16fc225-cbe1-462d-95e2-5299e3dbc7af",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5e81e088-9b31-4553-8dc7-0a1371569f61",
                            Email = "saeedabohend@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Saeed Abohend",
                            NormalizedEmail = "SAEEDABOHEND@EXAMPLE.COM",
                            NormalizedUserName = "SAEEDABOHEND@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEL8hekvqLd9hPhc+dsFN9f+8zI1b1dp4GhHtKSETlPiKbD+OEWo3IlxtQCp0/F5dwA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b01a1681-5945-41c2-89ce-3ec57a65b66f",
                            TwoFactorEnabled = false,
                            UserName = "saeedabohend@example.com"
                        },
                        new
                        {
                            Id = "75063820-8a33-4653-92da-0683da1f8a7a",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2c28df4d-b0de-4894-9ef8-a7a1a8238004",
                            Email = "abdoabohend@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "AbdoAbohend",
                            NormalizedEmail = "ABDOABOHEND@EXAMPLE.COM",
                            NormalizedUserName = "ABDOABOHEND@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEO401BDh2qtmLWLUVccIDuN4a95Yj4RXsnT+vfWkUrIISaeybwt3iAF5/mV916n8xQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0d5fbcc4-a205-4768-bf06-523054557368",
                            TwoFactorEnabled = false,
                            UserName = "abdoabohend@example.com"
                        },
                        new
                        {
                            Id = "36da79db-603c-4f7d-a641-9aea8632d1e9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f9bbe6de-682a-4715-9206-2abf99b44908",
                            Email = "ziadabohend@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Ziad Abohend",
                            NormalizedEmail = "ZIADABOHEND@EXAMPLE.COM",
                            NormalizedUserName = "ZIADABOHEND@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPI9Gq5z/7/jpRZhdovDnEhvU+OLb+8Ys0kGKn8IzBnD0zoKMwxewnX7HCraxIoLFg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3d17a7c0-ce8c-4c53-913e-f17338328ebe",
                            TwoFactorEnabled = false,
                            UserName = "ziadabohend@example.com"
                        });
                });

            modelBuilder.Entity("Ecommerce.Entities.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Fresh fruits",
                            Image = "images/categories/Fruits.png",
                            Name = "Fruits"
                        },
                        new
                        {
                            Id = 2,
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Fresh vegetables",
                            Image = "images/categories/Vegetables.jpg",
                            Name = "Vegetables"
                        },
                        new
                        {
                            Id = 3,
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "High quality bread",
                            Image = "images/categories/Bread.jpg",
                            Name = "Bread"
                        },
                        new
                        {
                            Id = 4,
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "All meat types",
                            Image = "images/categories/Meat.jpg",
                            Name = "Meat"
                        });
                });

            modelBuilder.Entity("Ecommerce.Entities.Models.ContactInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ContactInfos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Street, Nasr City, Egypt",
                            Email = "info@example.com",
                            Phone = "+201065964363"
                        });
                });

            modelBuilder.Entity("Ecommerce.Entities.Models.ContactMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ContactMessages");
                });

            modelBuilder.Entity("Ecommerce.Entities.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Carrier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentIntentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SessionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ShippingDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrackingNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Ecommerce.Entities.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Ecommerce.Entities.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Fresh grapes",
                            Image = "images/products/grapes.jpg",
                            Name = "Grapes",
                            Price = 4.99m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Fresh Raspberries",
                            Image = "images/products/Raspberries.jpg",
                            Name = "Raspberries",
                            Price = 5.99m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "Fresh brocoli",
                            Image = "images/products/Brocoli.jpg",
                            Name = "Brocoli",
                            Price = 2.5m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "High quality potatoes",
                            Image = "images/products/Potatoes.jpg",
                            Name = "Potatoes",
                            Price = 1.4m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Description = "Wellbacked breadsticks",
                            Image = "images/products/Breadsticks.jpg",
                            Name = "Breadsticks",
                            Price = 1.93m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Description = "Wellbacked croissant",
                            Image = "images/products/Croissant.jpg",
                            Name = "Croissant",
                            Price = 2.14m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            Description = "Basic cuts of beef",
                            Image = "images/products/Beef.jpg",
                            Name = "Beef",
                            Price = 9.14m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            Description = "Basic cuts of lamp meat",
                            Image = "images/products/Lamp.webp",
                            Name = "Lamp",
                            Price = 10.45m
                        });
                });

            modelBuilder.Entity("Ecommerce.Entities.Models.ShoppingCartItem", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.HasKey("ProductId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ShoppingCartItems");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = "1c92561a-2408-4442-960a-350cae3c2a51",
                            Name = "admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "6d229666-1485-462d-b795-8114ff6f6f5c",
                            Name = "customer",
                            NormalizedName = "CUSTOMER"
                        },
                        new
                        {
                            Id = "38f1fc3e-0483-4667-b6ce-0b5688d32089",
                            Name = "editor",
                            NormalizedName = "EDITOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RoleId", "UserId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            RoleId = "1c92561a-2408-4442-960a-350cae3c2a51",
                            UserId = "3d482e40-06df-4e49-9c41-68bad89689c3"
                        },
                        new
                        {
                            RoleId = "6d229666-1485-462d-b795-8114ff6f6f5c",
                            UserId = "e16fc225-cbe1-462d-95e2-5299e3dbc7af"
                        },
                        new
                        {
                            RoleId = "6d229666-1485-462d-b795-8114ff6f6f5c",
                            UserId = "75063820-8a33-4653-92da-0683da1f8a7a"
                        },
                        new
                        {
                            RoleId = "6d229666-1485-462d-b795-8114ff6f6f5c",
                            UserId = "36da79db-603c-4f7d-a641-9aea8632d1e9"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("Ecommerce.Entities.Models.Order", b =>
                {
                    b.HasOne("Ecommerce.Entities.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ecommerce.Entities.Models.OrderItem", b =>
                {
                    b.HasOne("Ecommerce.Entities.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ecommerce.Entities.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Ecommerce.Entities.Models.Product", b =>
                {
                    b.HasOne("Ecommerce.Entities.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Ecommerce.Entities.Models.ShoppingCartItem", b =>
                {
                    b.HasOne("Ecommerce.Entities.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ecommerce.Entities.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ecommerce.Entities.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
